CCC = g++ # C++ compiler
CCCFLAGS = -O2 -m64 -std=gnu++0x -Wall # Compiler flags (you probably don't need to change anything here)
CCCINC = -I../Common/ -I/data/bio/alexeygritsenk/apps/include/ # include directory
CCCLIB = -L/data/bio/alexeygritsenk/apps/lib/ -lbamtools # library directory and libraries

# Extra flags. Used for compiling scaffoldOptimizer (it uses the NCBI C++ Toolkit and CPLEX API)
CCEFLAGS = -fPIC -fexceptions -fopenmp -DNDEBUG -DIL_STD
CCEINC = -I/data/bio/alexeygritsenk/apps/ILOG/cplex/include -I/data/bio/alexeygritsenk/apps/ILOG/concert/include -I/data/bio/alexeygritsenk/apps/include/ncbi-tools++
CCELIB = -lxalgoalignnw -lxobjmgr -lgenome_collection -lseqset -lseqedit -lseq -lseqcode -lsequtil -lpub -lmedline -lbiblio -lgeneral -lxser -lxutil -lxncbi -ltables -L/data/bio/alexeygritsenk/apps/ILOG/cplex/lib/x86-64_sles10_4.1/static_pic -lilocplex -lcplex -L/data/bio/alexeygritsenk/apps/ILOG/concert/lib/x86-64_sles10_4.1/static_pic -lconcert -lm -pthread

# Do not change anything below unless (you think) you know what you're doing.
MAKE = make
MD = mkdir
CDIR = ../Common
ODIR = obj
BDIR = ../bin
